/**
 * Bertrand Basset Portfolio
 * Auto-generated by Admin V5
 */

const MENU_CONFIG = [
  {
    "id": "portrait",
    "name": "Accueil",
    "type": "gallery",
    "galleryId": "portrait"
  },
  {
    "id": "menu-1771800481065",
    "name": "Atelier",
    "type": "category",
    "children": [
      {
        "id": "menu-1771800619550",
        "name": "SERIE",
        "type": "gallery",
        "galleryId": null
      },
      {
        "id": "menu-1771800788803",
        "name": "Menu par image",
        "type": "gallery",
        "galleryId": null
      }
    ]
  },
  {
    "id": "menu-1771800487382",
    "name": "Studio",
    "type": "category",
    "children": [
      {
        "id": "menu-1771800574832",
        "name": "Headshot",
        "type": "gallery",
        "galleryId": null
      },
      {
        "id": "menu-1771800636336",
        "name": "REPORTAGE",
        "type": "gallery",
        "galleryId": null
      },
      {
        "id": "menu-1771800716438",
        "name": "Boutique",
        "type": "gallery",
        "galleryId": null
      }
    ]
  },
  {
    "id": "series",
    "name": "Séries",
    "type": "category",
    "children": [
      {
        "id": "burning-man-m",
        "name": "Burning Man",
        "type": "gallery",
        "galleryId": "burning-man"
      },
      {
        "id": "gem-m",
        "name": "Le GEM s'endimanche",
        "type": "gallery",
        "galleryId": "gem"
      },
      {
        "id": "carre-das-m",
        "name": "Carré d'As",
        "type": "gallery",
        "galleryId": "carre-das"
      },
      {
        "id": "st-melar-m",
        "name": "St Mélar",
        "type": "gallery",
        "galleryId": "st-melar"
      }
    ]
  },
  {
    "id": "other",
    "name": "Autres Travaux",
    "type": "page",
    "children": [
      {
        "id": "cinema-m",
        "name": "Cinéma",
        "type": "gallery",
        "galleryId": "cinema"
      },
      {
        "id": "tv-m",
        "name": "Télévision",
        "type": "gallery",
        "galleryId": "television"
      }
    ],
    "pageId": ""
  },
  {
    "id": "about-m",
    "name": "À propos",
    "type": "page",
    "pageId": "about"
  },
  {
    "id": "contact-m",
    "name": "Contact",
    "type": "page",
    "pageId": "contact"
  }
];

const GALLERIES_CONFIG = {
    "accueil": {
        title: "Accueil",
        path: "images/accueil",
        images: [
            { filename: "02.jpg" },
            { filename: "prise de vue sans titre-3616BB@SS.jpg" },
            { filename: "prise de vue sans titre-1220776Man&Pia.jpg" },
            { filename: "prise de vue sans titre-3610BB@SS.jpg" },
            { filename: "prise de vue sans titre-3653BB@SS.jpg", tirage: true },
            { filename: "prise de vue sans titre-5583BB@SS.jpg", tirage: true },
            { filename: "prise de vue sans titre-1010526Man&Pia.jpg" },
            { filename: "26062022- ORIANE-RESIDENCE-PARVIS PISCINE-3Man&Pia.jpg" },
            { filename: "prise de vue sans titre-1220771Man&Pia.jpg" },
            { filename: "prise de vue sans titre-1220777Man&Pia.jpg" },
            { filename: "prise de vue sans titre-1220784Man&Pia.jpg" },
            { filename: "prise de vue sans titre-1220830Man&Pia.jpg" },
            { filename: "prise de vue sans titre-3629BB@SS.jpg" },
            { filename: "prise de vue sans titre-3650BB@SS.jpg" },
            { filename: "AngeMarine18@bertrandbasset 18.jpg" }
        ]
    },
    "portrait": {
        title: "Portrait",
        path: "images/photography/portrait",
        images: [
            { filename: "02.jpg" },
            { filename: "AngeMarine18@bertrandbasset 18.jpg" },
            { filename: "L1020643.jpg" },
            { filename: "Stephanie06@bertrandbasset 6.jpg" },
            { filename: "Imane02@bertrandbasset 2.jpg" },
            { filename: "AngeMarine01@bertrandbasset 1.jpg" },
            { filename: "prise_de_vue_sans_titre-1000589-ModifierMan_Pia.jpg" },
            { filename: "AngeMarine13@bertrandbasset 13.jpg" },
            { filename: "Mathilde&Louise04@bertrandbasset 4.jpg" },
            { filename: "AngeMarine22@bertrandbasset 22.jpg" },
            { filename: "L1020630.jpg" },
            { filename: "prise_de_vue_sans_titre-8640Man_Pia.jpg" },
            { filename: "Stephanie05@bertrandbasset 5.jpg" },
            { filename: "AngeMarine20@bertrandbasset 20.jpg" },
            { filename: "prise_de_vue_sans_titre-2-385Man_Pia.jpg" },
            { filename: "prise_de_vue_sans_titre-7208Man_Pia.jpg" }
        ]
    },
    "headshot": {
        title: "Headshot",
        path: "images/photography/headshot",
        images: [
        ]
    },
    "gem": {
        title: "Le GEM s'endimanche",
        path: "images/photography/serie-portrait/gem",
        description: "Série de portraits réalisée au GEM de Morlaix. Chaque portrait est accompagné d'un témoignage audio.",
        autoplayAudio: true,
        images: [
            { filename: "ALain.jpg", audio: "ALain.mp3" },
            { filename: "Beatrice.jpg", audio: "Beatrice.mp3" },
            { filename: "Bernard.jpg", audio: "Bernard.mp3" },
            { filename: "Bruno.jpg" },
            { filename: "GUY.jpg" },
            { filename: "Helene.jpg", audio: "Helene.mp3" },
            { filename: "Jean-Pierre.jpg" },
            { filename: "JeanFrancois.jpg", audio: "JeanFrancois.mp3" },
            { filename: "Laurence.jpg" },
            { filename: "Patricia.jpg", audio: "Patricia.mp3" },
            { filename: "Theo.jpg", audio: "Theo.mp3" },
            { filename: "Veronique.jpg" },
            { filename: "VALERIE.jpg", audio: "VALERIE.mp3" }
        ]
    },
    "carre-das": {
        title: "Carré d'As",
        path: "images/photography/serie-portrait/Carré D'as",
        images: [
        ]
    },
    "burning-man": {
        title: "Burning Man",
        path: "images/photography/immersion/Burning Man",
        images: [
            { filename: "prise de vue sans titre-1890BB@SS.jpg" },
            { filename: "prise de vue sans titre-4480BB@SS.jpg" },
            { filename: "prise de vue sans titre-3616BB@SS.jpg" },
            { filename: "prise de vue sans titre-3610BB@SS.jpg" },
            { filename: "prise de vue sans titre-3629BB@SS.jpg" },
            { filename: "prise de vue sans titre-3650BB@SS.jpg" },
            { filename: "prise de vue sans titre-3653BB@SS.jpg" },
            { filename: "prise de vue sans titre-4182BB@SS.jpg" },
            { filename: "prise de vue sans titre-4184BB@SS.jpg" },
            { filename: "prise de vue sans titre-4264BB@SS.jpg" },
            { filename: "prise de vue sans titre-4318BB@SS.jpg" },
            { filename: "prise de vue sans titre-4378BB@SS.jpg" },
            { filename: "prise de vue sans titre-4403BB@SS.jpg" },
            { filename: "prise de vue sans titre-4405BB@SS.jpg" },
            { filename: "prise de vue sans titre-4423BB@SS.jpg" },
            { filename: "prise de vue sans titre-4449BB@SS.jpg" },
            { filename: "prise de vue sans titre-4463BB@SS.jpg" },
            { filename: "prise de vue sans titre-4473BB@SS.jpg" },
            { filename: "prise de vue sans titre-4511BB@SS.jpg" },
            { filename: "prise de vue sans titre-4565BB@SS.jpg" },
            { filename: "prise de vue sans titre-4645BB@SS.jpg" },
            { filename: "prise de vue sans titre-4753BB@SS.jpg" },
            { filename: "prise de vue sans titre-4757BB@SS.jpg" },
            { filename: "prise de vue sans titre-4769BB@SS.jpg" },
            { filename: "prise de vue sans titre-4788BB@SS.jpg" },
            { filename: "prise de vue sans titre-4931BB@SS.jpg" },
            { filename: "prise de vue sans titre-5150BB@SS.jpg" },
            { filename: "prise de vue sans titre-5356BB@SS.jpg" },
            { filename: "prise de vue sans titre-5432BB@SS.jpg" },
            { filename: "prise de vue sans titre-5583BB@SS.jpg" },
            { filename: "prise de vue sans titre-5768BB@SS.jpg" },
            { filename: "prise de vue sans titre-5896BB@SS.jpg" },
            { filename: "prise de vue sans titre-5903BB@SS.jpg" },
            { filename: "prise de vue sans titre-5912BB@SS.jpg" }
        ]
    },
    "st-melar": {
        title: "St Mélar",
        path: "images/photography/immersion/St Mélar",
        images: [
        ]
    },
    "cinema": {
        title: "Cinéma",
        path: "images/filmmaker/cinema",
        images: [
            { filename: "AFFICHE FILM J'ARRIVE.jpg" },
            { filename: "AFFICHE L'UN POUR L'AUTRE.jpg" },
            { filename: "AFFICHE KAPO.jpg" },
            { filename: "10-la famille-8.jpg" },
            { filename: "11-le-general-2.jpg" },
            { filename: "AFFICHE VISAGES.jpg" },
            { filename: "jarrive-making-of-85.jpg" },
            { filename: "jarrive-making-of-163.jpg" },
            { filename: "jarrive-making-of-127.jpg" }
        ]
    },
    "television": {
        title: "Télévision",
        path: "images/filmmaker/Television",
        images: [
            { filename: "01.jpg" },
            { filename: "02.jpg" },
            { filename: "03.jpg" },
            { filename: "04.jpg" },
            { filename: "07.jpg" },
            { filename: "08.jpg" },
            { filename: "09.jpg" },
            { filename: "06.jpg" },
            { filename: "05.jpg" },
            { filename: "10.jpg" }
        ]
    },
    "all-photo": {
        title: "ALL PHOTO",
        path: "images/",
        hidden: true,
        images: [
        ]
    },
};

const PAGES_CONFIG = {
  "about": {
    "title": "À propos",
    "content": "Portraitiste, \n\nJe fabrique des images et je raconte des histoires depuis plus de 20ans. \nArtistes, Artisans, Série artistique, immersion ou studio mobile lors d'un évènement.\n\nPlusieurs idées de collaborations sont visibles dans la page boutique, pour toutes autres idées, n'hésitez pas à m'écrire. \n\nBertrand Basset\nPhotographe & Réalisateur"
  },
  "contact": {
    "title": "Contact",
    "content": ""
  }
};

const PROJECT_PAGES = {};

const TRANSLATIONS = {
    en: { "prev": "prev", "next": "next", "show-thumbnails": "thumbnails", "play": "play", "pause": "pause", "buy-print": "Buy", "see-series": "See series", "learn-more": "Learn more" },
    fr: { "prev": "préc", "next": "suiv", "show-thumbnails": "vignettes", "play": "écouter", "pause": "pause", "buy-print": "Acheter", "see-series": "Voir la série", "learn-more": "En savoir plus" }
};

class Portfolio {
    constructor() {
        this.galleries = this.buildGalleries();
        this.currentGallery = null;
        this.currentIndex = 0;
        this.isTransitioning = false;
        this.currentAudio = null;
        this.isPlaying = false;
        this.currentLang = 'fr';
        this.autoplayAudio = false;
        this.init();
    }

    buildGalleries() {
        const galleries = {};
        for (const [id, config] of Object.entries(GALLERIES_CONFIG)) {
            const items = [];
            if (config.description) items.push({ type: 'description', title: config.title, text: config.description });
            config.images.forEach(img => {
                items.push({
                    type: 'image',
                    src: `${config.path}/${img.filename}`,
                    title: img.title || '',
                    subtitle: img.subtitle || '',
                    description: img.description || '',
                    audio: img.audio ? `${config.path}/${img.audio}` : null,
                    tirage: img.tirage,
                    tirageUrl: img.tirageUrl,
                    linkSerie: img.linkSerie,
                    linkSerieTarget: img.linkSerieTarget,
                    linkSavoir: img.linkSavoir,
                    linkSavoirUrl: img.linkSavoirUrl
                });
            });
            galleries[id] = { ...config, items };
        }
        return galleries;
    }

    init() {
        this.cacheElements();
        this.bindEvents();
        this.openGallery('accueil');
    }

    cacheElements() {
        this.landing = document.getElementById('landing');
        this.site = document.getElementById('site');
        this.enterBtn = document.getElementById('enterBtn');
        this.menuToggle = document.getElementById('menuToggle');
        this.mainNav = document.getElementById('mainNav');
        this.galleryContainer = document.getElementById('galleryContainer');
        this.galleryCounter = document.querySelector('.gallery-counter');
        this.imageInfo = document.querySelector('.image-info');
        this.audioControls = document.querySelector('.audio-controls');
        this.audioBtn = document.getElementById('audioBtn');
        this.homeLink = document.getElementById('homeLink');
        this.navItems = document.querySelectorAll('.nav-item[data-expandable]');
        this.dropdownLinks = document.querySelectorAll('[data-gallery]');
        this.pageLinks = document.querySelectorAll('[data-page]');
    }

    bindEvents() {
        if (this.enterBtn) this.enterBtn.onclick = () => this.enterSite();
        if (this.homeLink) this.homeLink.onclick = e => { e.preventDefault(); this.openGallery('accueil'); };
        if (this.menuToggle) this.menuToggle.onclick = () => this.toggleMenu();
        
        this.navItems.forEach(item => {
            const link = item.querySelector('.nav-link');
            if (link) link.onclick = e => { e.preventDefault(); item.classList.toggle('open'); };
        });
        
        this.dropdownLinks.forEach(link => {
            link.onclick = e => { e.preventDefault(); this.openGallery(link.dataset.gallery); this.closeMenu(); };
        });
        
        this.pageLinks.forEach(link => {
            link.onclick = e => { e.preventDefault(); this.showPage(link.dataset.page); this.closeMenu(); };
        });
        
        if (this.galleryContainer) {
            this.galleryContainer.onclick = e => {
                if (e.target.closest('.video-container, .buy-button, .image-link')) return;
                const rect = this.galleryContainer.getBoundingClientRect();
                (e.clientX - rect.left) < rect.width / 2 ? this.prev() : this.next();
            };
        }
        
        if (this.audioBtn) this.audioBtn.onclick = () => this.toggleAudio();
        
        document.onkeydown = e => {
            if (e.key === 'ArrowLeft') this.prev();
            if (e.key === 'ArrowRight') this.next();
            if (e.key === ' ') { e.preventDefault(); this.toggleAudio(); }
        };
        
        this.initSwipe();
    }

    enterSite() { this.landing?.classList.add('hidden'); this.site?.classList.add('active'); }
    toggleMenu() { this.menuToggle?.classList.toggle('open'); this.mainNav?.classList.toggle('open'); }
    closeMenu() { this.menuToggle?.classList.remove('open'); this.mainNav?.classList.remove('open'); }

    openGallery(id) {
        const g = this.galleries[id];
        if (!g?.items.length) return;
        this.currentGallery = g;
        this.currentGalleryId = id;
        this.currentIndex = 0;
        this.autoplayAudio = g.autoplayAudio || false;
        this.showItem(0);
    }

    showItem(index) {
        if (!this.currentGallery || this.isTransitioning) return;
        const items = this.currentGallery.items;
        if (index < 0 || index >= items.length) return;
        
        this.stopAudio();
        this.isTransitioning = true;
        this.currentIndex = index;
        const item = items[index];
        
        setTimeout(() => {
            this.galleryContainer.innerHTML = '';
            
            if (item.type === 'description') {
                this.galleryContainer.innerHTML = `<div class="description-slide loaded"><div class="description-content"><h2>${item.title}</h2><p>${item.text}</p></div></div>`;
            } else {
                const wrapper = document.createElement('div');
                wrapper.className = 'image-wrapper';
                const img = document.createElement('img');
                img.className = 'gallery-image';
                img.onload = () => { img.classList.add('loaded'); this.isTransitioning = false; };
                img.src = encodeURI(item.src);
                wrapper.appendChild(img);
                
                // Buy button
                if (item.tirage && item.tirageUrl) {
                    const btn = document.createElement('a');
                    btn.className = 'buy-button';
                    btn.href = item.tirageUrl;
                    btn.target = '_blank';
                    btn.textContent = '🛒 ' + TRANSLATIONS[this.currentLang]['buy-print'];
                    wrapper.appendChild(btn);
                }
                
                this.galleryContainer.appendChild(wrapper);
                if (item.audio && this.autoplayAudio) this.playAudio(item.audio);
            }
            
            this.updateUI(item);
            this.isTransitioning = false;
        }, 200);
    }

    updateUI(item) {
        if (this.galleryCounter) this.galleryCounter.textContent = `${this.currentIndex + 1} / ${this.currentGallery.items.length}`;
        
        // Update sidebar info
        if (this.imageInfo) {
            let html = '';
            if (item.title) html += `<h3 class="image-title">${item.title}</h3>`;
            if (item.subtitle) html += `<p class="image-subtitle">${item.subtitle}</p>`;
            if (item.description) html += `<p class="image-description">${item.description}</p>`;
            if (item.linkSerie && item.linkSerieTarget) {
                html += `<a href="#" class="image-link" onclick="event.preventDefault();portfolio.openGallery('${item.linkSerieTarget}')">${TRANSLATIONS[this.currentLang]['see-series']} →</a>`;
            }
            if (item.linkSavoir && item.linkSavoirUrl) {
                html += `<a href="${item.linkSavoirUrl}" target="_blank" class="image-link">${TRANSLATIONS[this.currentLang]['learn-more']} →</a>`;
            }
            this.imageInfo.innerHTML = html;
        }
        
        if (this.audioControls) this.audioControls.classList.toggle('visible', item.type === 'image' && !!item.audio);
    }

    prev() { if (this.currentGallery) this.showItem(this.currentIndex > 0 ? this.currentIndex - 1 : this.currentGallery.items.length - 1); }
    next() { if (this.currentGallery) this.showItem(this.currentIndex < this.currentGallery.items.length - 1 ? this.currentIndex + 1 : 0); }

    playAudio(src) {
        this.stopAudio();
        this.currentAudio = new Audio(encodeURI(src));
        this.currentAudio.play().catch(() => {});
        this.isPlaying = true;
        this.updateAudioBtn();
        this.currentAudio.onended = () => { this.isPlaying = false; this.updateAudioBtn(); };
    }
    
    stopAudio() { 
        if (this.currentAudio) { this.currentAudio.pause(); this.currentAudio = null; } 
        this.isPlaying = false; 
        this.updateAudioBtn(); 
    }
    
    toggleAudio() {
        const item = this.currentGallery?.items[this.currentIndex];
        if (!item?.audio) return;
        this.isPlaying ? this.stopAudio() : this.playAudio(item.audio);
    }
    
    updateAudioBtn() {
        if (!this.audioBtn) return;
        this.audioBtn.innerHTML = this.isPlaying ? '⏸' : '▶';
        this.audioBtn.classList.toggle('playing', this.isPlaying);
    }

    showPage(id) {
        const page = PAGES_CONFIG[id];
        if (!page) return;
        this.currentGallery = null;
        if (this.galleryCounter) this.galleryCounter.style.display = 'none';
        if (this.audioControls) this.audioControls.classList.remove('visible');
        if (this.imageInfo) this.imageInfo.innerHTML = '';
        
        let html = `<div class="page-content"><div class="page-text">${page.content.replace(/\n/g, '<br>')}</div>`;
        if (page.price) html += `<div class="page-price">${page.price}</div>`;
        if (page.link) html += `<a class="page-btn" href="${page.link}" target="_blank">Réserver</a>`;
        html += '</div>';
        this.galleryContainer.innerHTML = html;
    }

    initSwipe() {
        let startX;
        this.galleryContainer?.addEventListener('touchstart', e => startX = e.touches[0].clientX);
        this.galleryContainer?.addEventListener('touchend', e => {
            const diff = startX - e.changedTouches[0].clientX;
            if (Math.abs(diff) > 50) diff > 0 ? this.next() : this.prev();
        });
    }
}

document.addEventListener('DOMContentLoaded', () => window.portfolio = new Portfolio());
