/**
 * Bertrand Basset Portfolio - V8
 * Generated by Admin
 */

const GALLERIES_CONFIG = {
    "accueil": {
        title: "Accueil",
        path: "images/accueil",
        images: [
            "prise de vue sans titre-3616BB@SS.jpg",
            "prise de vue sans titre-1220776Man&Pia.jpg",
            "prise de vue sans titre-3610BB@SS.jpg",
            "prise de vue sans titre-3653BB@SS.jpg",
            "prise de vue sans titre-5583BB@SS.jpg",
            "prise de vue sans titre-1010526Man&Pia.jpg",
            "26062022- ORIANE-RESIDENCE-PARVIS PISCINE-3Man&Pia.jpg",
            "prise de vue sans titre-1220771Man&Pia.jpg",
            "prise de vue sans titre-1220777Man&Pia.jpg",
            "prise de vue sans titre-1220784Man&Pia.jpg",
            "prise de vue sans titre-1220830Man&Pia.jpg",
            "prise de vue sans titre-3629BB@SS.jpg",
            "prise de vue sans titre-3650BB@SS.jpg"
        ]
    },
    "portrait": {
        title: "Portrait",
        path: "images/photography/portrait",
        images: [
            "02.jpg",
            "AngeMarine18@bertrandbasset 18.jpg",
            "L1020643.jpg",
            "Stephanie06@bertrandbasset 6.jpg",
            "Imane02@bertrandbasset 2.jpg",
            "AngeMarine01@bertrandbasset 1.jpg",
            "Timoté01@bertrandbasset 1.jpg",
            "prise_de_vue_sans_titre-1000589-ModifierMan_Pia.jpg",
            "AngeMarine13@bertrandbasset 13.jpg",
            "Mathilde&Louise04@bertrandbasset 4.jpg",
            "AngeMarine22@bertrandbasset 22.jpg",
            "L1020630.jpg",
            "prise_de_vue_sans_titre-8640Man_Pia.jpg",
            "Stephanie05@bertrandbasset 5.jpg",
            "AngeMarine20@bertrandbasset 20.jpg",
            "prise_de_vue_sans_titre-2-385Man_Pia.jpg",
            "prise_de_vue_sans_titre-7208Man_Pia.jpg"
        ]
    },
    "gem": {
        title: "Le GEM s'endimanche",
        path: "images/photography/serie-portrait/gem",
        description: "Série de portraits réalisée au GEM de Morlaix. Chaque portrait est accompagné d'un témoignage audio.",
        projectTitle: "Le GEM s'endimanche",
        projectLink: "projects/le-gem.html",
        images: [
            { filename: "ALain.jpg", audio: "ALain.mp3" },
            { filename: "Beatrice.jpg", audio: "Beatrice.mp3" },
            { filename: "Bernard.jpg", audio: "Bernard.mp3" },
            "Bruno.jpg",
            "GUY.jpg",
            { filename: "Helene.jpg", audio: "Helene.mp3" },
            "Jean-Pierre.jpg",
            { filename: "JeanFrancois.jpg", audio: "JeanFrancois.mp3" },
            "Laurence.jpg",
            { filename: "Patricia.jpg", audio: "Patricia.mp3" },
            { filename: "Theo.jpg", audio: "Theo.mp3" },
            "Veronique.jpg",
            { filename: "VALERIE.jpg", audio: "VALERIE.mp3" }
        ]
    },
    "carre-das": {
        title: "Carré d'As",
        path: "images/photography/serie-portrait/Carré D'as",
        images: [
        ]
    },
    "burning-man": {
        title: "Burning Man",
        path: "images/photography/immersion/Burning Man",
        images: [
            "prise de vue sans titre-1890BB@SS.jpg",
            "prise de vue sans titre-4480BB@SS.jpg",
            "prise de vue sans titre-2453BB@SS.jpg",
            "prise de vue sans titre-2510BB@SS.jpg",
            "prise de vue sans titre-4539BB@SS.jpg",
            "prise de vue sans titre-2663BB@SS.jpg",
            "prise de vue sans titre-2850BB@SS.jpg",
            "prise de vue sans titre-2884-ModifierBB@SS.jpg",
            "prise de vue sans titre-2980BB@SS.jpg",
            "prise de vue sans titre-3187BB@SS.jpg",
            "prise de vue sans titre-3229BB@SS.jpg",
            "prise de vue sans titre-3421BB@SS.jpg",
            "prise de vue sans titre-3578BB@SS.jpg",
            "prise de vue sans titre-3593BB@SS.jpg",
            "prise de vue sans titre-3600BB@SS.jpg",
            "prise de vue sans titre-3610BB@SS.jpg",
            "prise de vue sans titre-3614BB@SS.jpg",
            "prise de vue sans titre-3616BB@SS.jpg",
            "prise de vue sans titre-3629BB@SS.jpg",
            "prise de vue sans titre-3637-ModifierBB@SS.jpg",
            "prise de vue sans titre-3650BB@SS.jpg",
            "prise de vue sans titre-3653BB@SS.jpg",
            "prise de vue sans titre-4531BB@SS.jpg",
            "prise de vue sans titre-5378BB@SS.jpg",
            "prise de vue sans titre-5380BB@SS.jpg",
            "prise de vue sans titre-5543BB@SS.jpg",
            "prise de vue sans titre-5583BB@SS.jpg",
            "prise de vue sans titre-5606BB@SS.jpg",
            "prise de vue sans titre-5986BB@SS.jpg",
            "prise de vue sans titre-6273BB@SS.jpg",
            "prise de vue sans titre-6280BB@SS.jpg",
            "prise de vue sans titre-6290BB@SS.jpg",
            "prise de vue sans titre-6292BB@SS.jpg",
            "prise de vue sans titre-6294BB@SS.jpg"
        ]
    },
    "st-melar": {
        title: "St Mélar",
        path: "images/photography/immersion/St Mélar",
        images: [
        ]
    },
    "cinema": {
        title: "Cinéma",
        path: "images/filmmaker/cinema",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg"
        ]
    },
    "television": {
        title: "Télévision",
        path: "images/filmmaker/Television",
        description: "Portraits d'invités du 20h30 le dimanche à partir d'archives, ainsi que des films documentaire sur l'histoire de la télévision, le commando Kieffer, ou encore Armel Le Cleac'h",
        images: [
            "01.jpg",
            "02.jpg",
            "03.jpg",
            "04.jpg",
            "05.jpg",
            "06.jpg",
            "07.jpg",
            "08.jpg",
            "09.jpg",
            "10.jpg"
        ]
    },
};

const PAGES_CONTENT = {
    about: { title: "À propos", content: "Bertrand Basset\nPhotographe & Réalisateur\n\nBasé en Bretagne." },
    contact: { title: "Contact", content: "bertrand.basset@gmail.com" }
};

const TRANSLATIONS = {
    en: { "photography": "Photography", "portrait": "Portrait", "serie-portrait": "Serie Portrait", "immersion": "Immersion", "filmmaker": "Filmmaker", "cinema": "Cinema", "television": "Television", "about": "About", "contact": "Contact", "learn-more": "learn more", "prev": "prev", "next": "next", "show-thumbnails": "show thumbnails", "hide-thumbnails": "hide thumbnails", "play": "play", "pause": "pause" },
    fr: { "photography": "Photographie", "portrait": "Portrait", "serie-portrait": "Série Portrait", "immersion": "Immersion", "filmmaker": "Réalisateur", "cinema": "Cinéma", "television": "Télévision", "about": "À propos", "contact": "Contact", "learn-more": "en savoir plus", "prev": "préc", "next": "suiv", "show-thumbnails": "voir vignettes", "hide-thumbnails": "masquer vignettes", "play": "écouter", "pause": "pause" }
};

class Portfolio {
    constructor() {
        this.galleries = this.buildGalleries();
        this.currentGallery = null;
        this.currentIndex = 0;
        this.isTransitioning = false;
        this.currentAudio = null;
        this.isPlaying = false;
        this.currentLang = 'fr';
        this.isMobile = window.innerWidth <= 768;
        this.currentPage = null;
        this.init();
    }

    buildGalleries() {
        const galleries = {};
        for (const [id, config] of Object.entries(GALLERIES_CONFIG)) {
            const items = [];
            if (config.description) items.push({ type: 'description', title: config.title, text: config.description });
            if (config.videos) config.videos.forEach(v => items.push({ type: 'video', platform: v.type, videoId: v.id, title: v.title || '' }));
            config.images.forEach(img => {
                if (typeof img === 'string') items.push({ type: 'image', src: `${config.path}/${img}`, caption: '' });
                else items.push({ type: 'image', src: `${config.path}/${img.filename}`, caption: img.caption || '', audio: img.audio ? `${config.path}/${img.audio}` : null });
            });
            galleries[id] = { title: config.title, description: config.description || '', projectTitle: config.projectTitle || null, projectLink: config.projectLink || null, items };
        }
        return galleries;
    }

    init() { this.cacheElements(); this.bindEvents(); this.openGallery('accueil'); this.handleResize(); }

    cacheElements() {
        this.landing = document.getElementById('landing');
        this.site = document.getElementById('site');
        this.enterBtn = document.getElementById('enterBtn');
        this.menuToggle = document.getElementById('menuToggle');
        this.mainNav = document.getElementById('mainNav');
        this.galleryContainer = document.getElementById('galleryContainer');
        this.prevBtn = document.getElementById('prevBtn');
        this.nextBtn = document.getElementById('nextBtn');
        this.thumbnailsToggle = document.getElementById('thumbnailsToggle');
        this.thumbnailsPanel = document.getElementById('thumbnailsPanel');
        this.thumbnailsGrid = document.getElementById('thumbnailsGrid');
        this.thumbnailsClose = document.getElementById('thumbnailsClose');
        this.galleryCounter = document.querySelector('.gallery-counter');
        this.imageCaption = document.querySelector('.image-caption');
        this.navItems = document.querySelectorAll('.nav-item[data-expandable]');
        this.dropdownLinks = document.querySelectorAll('.dropdown-link:not(.has-submenu)');
        this.submenuLinks = document.querySelectorAll('.dropdown-link.has-submenu');
        this.dropdownSublinks = document.querySelectorAll('.dropdown-sublink');
        this.projectInfo = document.querySelector('.project-info');
        this.projectTitle = document.querySelector('.project-title');
        this.projectLink = document.querySelector('.project-link');
        this.audioControls = document.querySelector('.audio-controls');
        this.audioBtn = document.getElementById('audioBtn');
        this.homeLink = document.getElementById('homeLink');
        this.langLinks = document.querySelectorAll('[data-lang]');
        this.cursor = document.getElementById('customCursor');
    }

    bindEvents() {
        if (this.enterBtn) this.enterBtn.addEventListener('click', () => this.enterSite());
        if (this.homeLink) this.homeLink.addEventListener('click', (e) => { e.preventDefault(); this.currentPage = null; this.openGallery('accueil'); this.closeMenu(); });
        if (this.menuToggle) this.menuToggle.addEventListener('click', () => this.toggleMenu());
        this.navItems.forEach(item => { const link = item.querySelector('.nav-link'); if (link) link.addEventListener('click', (e) => { e.preventDefault(); this.toggleNavItem(item); }); });
        this.dropdownLinks.forEach(link => { link.addEventListener('click', (e) => { e.preventDefault(); const gid = link.dataset.gallery; if (gid) { this.currentPage = null; this.openGallery(gid); this.closeMenu(); } }); });
        this.submenuLinks.forEach(link => { link.addEventListener('click', (e) => { e.preventDefault(); link.classList.toggle('open'); }); });
        this.dropdownSublinks.forEach(link => { link.addEventListener('click', (e) => { e.preventDefault(); const gid = link.dataset.gallery; if (gid) { this.currentPage = null; this.openGallery(gid); this.closeMenu(); } }); });
        document.querySelectorAll('[data-page]').forEach(link => { link.addEventListener('click', (e) => { e.preventDefault(); this.showPage(link.dataset.page); this.closeMenu(); }); });
        if (this.prevBtn) this.prevBtn.addEventListener('click', (e) => { e.preventDefault(); this.prevItem(); });
        if (this.nextBtn) this.nextBtn.addEventListener('click', (e) => { e.preventDefault(); this.nextItem(); });
        if (this.galleryContainer) {
            this.galleryContainer.addEventListener('click', (e) => {
                if (e.target.closest('.video-container') || this.currentPage) return;
                const rect = this.galleryContainer.getBoundingClientRect();
                if ((e.clientX - rect.left) < rect.width / 2) this.prevItem(); else this.nextItem();
            });
            this.galleryContainer.addEventListener('mousemove', (e) => {
                if (!this.isMobile && this.cursor) {
                    this.cursor.style.left = e.clientX + 'px';
                    this.cursor.style.top = e.clientY + 'px';
                    const rect = this.galleryContainer.getBoundingClientRect();
                    this.cursor.innerHTML = (e.clientX - rect.left) < rect.width / 2 ? '<svg viewBox="0 0 24 24"><polyline points="15,6 9,12 15,18"></polyline></svg>' : '<svg viewBox="0 0 24 24"><polyline points="9,6 15,12 9,18"></polyline></svg>';
                }
            });
            this.galleryContainer.addEventListener('mouseenter', () => { if (!this.isMobile && this.cursor) this.cursor.classList.add('visible'); });
            this.galleryContainer.addEventListener('mouseleave', () => { if (this.cursor) this.cursor.classList.remove('visible'); });
        }
        if (this.thumbnailsToggle) this.thumbnailsToggle.addEventListener('click', (e) => { e.preventDefault(); this.toggleThumbnails(); });
        if (this.thumbnailsClose) this.thumbnailsClose.addEventListener('click', () => this.hideThumbnails());
        if (this.audioBtn) this.audioBtn.addEventListener('click', (e) => { e.preventDefault(); this.toggleAudio(); });
        document.addEventListener('keydown', (e) => this.handleKeyboard(e));
        this.initSwipe();
        this.langLinks.forEach(link => { link.addEventListener('click', (e) => { e.preventDefault(); this.setLanguage(link.dataset.lang); }); });
        window.addEventListener('resize', () => this.handleResize());
    }

    toggleMenu() { if (this.menuToggle) this.menuToggle.classList.toggle('open'); if (this.mainNav) this.mainNav.classList.toggle('open'); }
    closeMenu() { if (this.menuToggle) this.menuToggle.classList.remove('open'); if (this.mainNav) this.mainNav.classList.remove('open'); }
    handleResize() { this.isMobile = window.innerWidth <= 768; if (!this.isMobile) this.closeMenu(); }
    enterSite() { if (this.landing) this.landing.classList.add('hidden'); if (this.site) this.site.classList.add('active'); }
    toggleNavItem(item) { const wasOpen = item.classList.contains('open'); this.navItems.forEach(n => { if (n !== item) n.classList.remove('open'); }); item.classList.toggle('open', !wasOpen); }

    showPage(pageId) {
        const page = PAGES_CONTENT[pageId];
        if (!page) return;
        this.currentPage = pageId;
        this.currentGallery = null;
        this.stopAudio();
        if (this.galleryCounter) this.galleryCounter.style.display = 'none';
        if (this.thumbnailsToggle) this.thumbnailsToggle.style.display = 'none';
        if (this.audioControls) this.audioControls.classList.remove('visible');
        if (this.projectInfo) this.projectInfo.classList.remove('visible');
        this.galleryContainer.innerHTML = `<div class="page-content"><div class="page-text">${page.content.replace(/\n/g, '<br>')}</div></div>`;
        this.galleryContainer.classList.add('page-mode');
    }

    openGallery(galleryId) {
        const gallery = this.galleries[galleryId];
        if (!gallery || !gallery.items.length) return;
        this.currentGallery = gallery;
        this.currentGalleryId = galleryId;
        this.currentIndex = 0;
        this.currentPage = null;
        if (this.galleryCounter) this.galleryCounter.style.display = '';
        if (this.thumbnailsToggle) this.thumbnailsToggle.style.display = '';
        this.galleryContainer.classList.remove('page-mode');
        this.showItem(0);
        this.generateThumbnails();
        this.updateProjectInfo();
    }

    showItem(index) {
        if (!this.currentGallery || this.isTransitioning) return;
        const items = this.currentGallery.items;
        if (index < 0 || index >= items.length) return;
        this.stopAudio();
        this.isTransitioning = true;
        this.currentIndex = index;
        const item = items[index];
        const current = this.galleryContainer.querySelector('.gallery-image, .description-slide, .video-container');
        if (current) current.classList.add('transitioning');
        setTimeout(() => {
            this.galleryContainer.innerHTML = '';
            if (item.type === 'description') this.showDescriptionSlide(item);
            else if (item.type === 'video') this.showVideoSlide(item);
            else this.showImageSlide(item);
            this.updateCounter();
            this.updateActiveThumbnail(index);
            this.updateAudioControls(item);
        }, 250);
    }

    showDescriptionSlide(item) {
        const div = document.createElement('div');
        div.className = 'description-slide';
        div.innerHTML = `<div class="description-content"><h2 class="description-title">${item.title}</h2><p class="description-text">${item.text}</p></div>`;
        this.galleryContainer.appendChild(div);
        setTimeout(() => { div.classList.add('loaded'); this.isTransitioning = false; }, 50);
        if (this.imageCaption) this.imageCaption.textContent = '';
    }

    showVideoSlide(item) {
        const div = document.createElement('div');
        div.className = 'video-container';
        const url = item.platform === 'vimeo' ? `https://player.vimeo.com/video/${item.videoId}?title=0&byline=0&portrait=0` : `https://www.youtube.com/embed/${item.videoId}?rel=0`;
        div.innerHTML = `<iframe src="${url}" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`;
        this.galleryContainer.appendChild(div);
        setTimeout(() => { div.classList.add('loaded'); this.isTransitioning = false; }, 50);
        if (this.imageCaption) this.imageCaption.textContent = item.title || '';
    }

    showImageSlide(item) {
        const img = document.createElement('img');
        img.className = 'gallery-image';
        img.alt = item.caption || '';
        img.loading = 'lazy';
        img.onload = () => { img.classList.add('loaded'); this.isTransitioning = false; };
        img.onerror = () => { this.isTransitioning = false; };
        this.galleryContainer.appendChild(img);
        img.src = encodeURI(item.src);
        if (this.imageCaption) this.imageCaption.textContent = item.caption || '';
        if (item.audio) this.playAudio(item.audio);
    }

    updateAudioControls(item) { if (this.audioControls) this.audioControls.classList.toggle('visible', item.type === 'image' && !!item.audio); }
    prevItem() { if (!this.currentGallery || this.currentPage) return; this.showItem(this.currentIndex > 0 ? this.currentIndex - 1 : this.currentGallery.items.length - 1); }
    nextItem() { if (!this.currentGallery || this.currentPage) return; this.showItem(this.currentIndex < this.currentGallery.items.length - 1 ? this.currentIndex + 1 : 0); }
    updateCounter() { if (this.galleryCounter && this.currentGallery) this.galleryCounter.textContent = `${this.currentIndex + 1} / ${this.currentGallery.items.length}`; }

    playAudio(src) { this.stopAudio(); this.currentAudio = new Audio(encodeURI(src)); this.currentAudio.play().catch(() => {}); this.isPlaying = true; this.updateAudioButton(); this.currentAudio.addEventListener('ended', () => { this.isPlaying = false; this.updateAudioButton(); }); }
    stopAudio() { if (this.currentAudio) { this.currentAudio.pause(); this.currentAudio = null; this.isPlaying = false; this.updateAudioButton(); } }
    toggleAudio() { if (!this.currentGallery) return; const item = this.currentGallery.items[this.currentIndex]; if (!item || !item.audio) return; if (this.isPlaying) this.stopAudio(); else this.playAudio(item.audio); }
    updateAudioButton() { if (!this.audioBtn) return; const icon = this.audioBtn.querySelector('.audio-icon'); const label = this.audioBtn.querySelector('.audio-label'); if (this.isPlaying) { if (icon) icon.innerHTML = '&#9724;'; if (label) label.textContent = this.t('pause'); this.audioBtn.classList.add('playing'); } else { if (icon) icon.innerHTML = '&#9654;'; if (label) label.textContent = this.t('play'); this.audioBtn.classList.remove('playing'); } }

    handleKeyboard(e) { if (!this.site || !this.site.classList.contains('active') || this.currentPage) return; if (e.key === 'ArrowLeft') { e.preventDefault(); this.prevItem(); } if (e.key === 'ArrowRight') { e.preventDefault(); this.nextItem(); } if (e.key === 'Escape') { this.hideThumbnails(); this.closeMenu(); } if (e.key === ' ') { e.preventDefault(); this.toggleAudio(); } }
    initSwipe() { if (!this.galleryContainer) return; let startX = 0, startY = 0; this.galleryContainer.addEventListener('touchstart', (e) => { startX = e.changedTouches[0].screenX; startY = e.changedTouches[0].screenY; }, { passive: true }); this.galleryContainer.addEventListener('touchend', (e) => { if (this.currentPage) return; const diffX = startX - e.changedTouches[0].screenX; const diffY = Math.abs(startY - e.changedTouches[0].screenY); if (Math.abs(diffX) > 50 && diffY < 100) { if (diffX > 0) this.nextItem(); else this.prevItem(); } }, { passive: true }); }

    toggleThumbnails() { if (this.thumbnailsPanel) { this.thumbnailsPanel.classList.toggle('active'); if (this.thumbnailsToggle) this.thumbnailsToggle.textContent = this.thumbnailsPanel.classList.contains('active') ? this.t('hide-thumbnails') : this.t('show-thumbnails'); } }
    hideThumbnails() { if (this.thumbnailsPanel) { this.thumbnailsPanel.classList.remove('active'); if (this.thumbnailsToggle) this.thumbnailsToggle.textContent = this.t('show-thumbnails'); } }
    generateThumbnails() { if (!this.thumbnailsGrid || !this.currentGallery) return; this.thumbnailsGrid.innerHTML = ''; this.currentGallery.items.forEach((item, i) => { const thumb = document.createElement('div'); thumb.className = 'thumbnail-item' + (i === this.currentIndex ? ' active' : ''); if (item.type === 'description') { thumb.innerHTML = '<span class="thumb-text">T</span>'; thumb.classList.add('thumb-description'); } else if (item.type === 'video') { thumb.innerHTML = '<span class="thumb-video">▶</span>'; thumb.classList.add('thumb-video-item'); } else { const img = document.createElement('img'); img.src = encodeURI(item.src); img.loading = 'lazy'; thumb.appendChild(img); } thumb.addEventListener('click', () => this.showItem(i)); this.thumbnailsGrid.appendChild(thumb); }); }
    updateActiveThumbnail(index) { if (!this.thumbnailsGrid) return; this.thumbnailsGrid.querySelectorAll('.thumbnail-item').forEach((t, i) => t.classList.toggle('active', i === index)); }
    updateProjectInfo() { if (!this.projectInfo || !this.currentGallery) return; if (this.currentGallery.projectTitle) { if (this.projectTitle) this.projectTitle.textContent = this.currentGallery.projectTitle; if (this.projectLink) this.projectLink.href = this.currentGallery.projectLink || '#'; this.projectInfo.classList.add('visible'); } else { this.projectInfo.classList.remove('visible'); } }
    setLanguage(lang) { if (!TRANSLATIONS[lang]) return; this.currentLang = lang; this.langLinks.forEach(l => l.classList.toggle('active', l.dataset.lang === lang)); document.querySelectorAll('[data-i18n]').forEach(el => { const key = el.dataset.i18n; if (TRANSLATIONS[lang][key]) el.textContent = TRANSLATIONS[lang][key]; }); }
    t(key) { return TRANSLATIONS[this.currentLang][key] || key; }
}

document.addEventListener('DOMContentLoaded', () => { window.portfolio = new Portfolio(); });